config/routes.rb
Bpifind::Application.routes.draw do

  root :to => 'home#index'
  devise_for :users

  namespace :admin do
		match '/' => 'dashboard#index'	
		get 'search'
		get 'filter'
		get 'reset'
		resources :collections do
			resources :harvest_logs do
				collection do
					get 'destroy_all'
				end
			end
		end
  	resources :collections_groups 
  	resources :collection_types
		resources :harvest_schedules 
		resources :harvest_logs 
		resources :parameters 
  	resources :users 
  end
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  attr_accessible :name, :value, :description
	validates_presence_of :name, :value

	def label
		"#{name} (#{value})"
	end

	class << self
		def search(q)
			where('name LIKE ? OR value LIKE ? OR description LIKE ?', q, q, q)
		end
	end
end

app/controllers/admin/parameters_controller.rb
class Admin::ParametersController < AdminController
	
	before_filter :find_parameter, :only => [:show, :edit, :update]

	def find_parameter
    @parameter = Parameter.find(params[:id])
	end

  def index
    @objects = Parameter.order(Parameter.sort_column).page(params[:page])
  end

  def new
    @parameter = Parameter.new
  end

  def create
    @parameter = Parameter.new(params[:parameter])
		if @parameter.save
			redirect_to admin_parameters_url, notice: t('parameter.created', :name => @parameter.name) 
		else
			render action: "new" 
		end
  end

  def update
		if @parameter.update_attributes(params[:parameter])
			redirect_to admin_parameters_url, notice: t('parameter.updated', :name => @parameter.name) 
		else
			render action: "edit" 
		end
  end

end

app/views/admin/parameters/_form.html.haml
= simple_form_for [:admin, @parameter], :html => {:class => 'form-horizontal'} do |f|
	= f.input :name, :disabled => @parameter.new_record? ? false : true
	= f.input :description
	= f.input :value
	= f.button :submit
	= link_to 'Annuler', admin_parameters_path, :class => 'btn'

app/views/admin/parameters/_listing.html.haml
- unless parameters.empty?

	= paginate parameters
	%table.table
		%tr
			%th= t('parameter.name').html_safe
			%th= t('parameter.description').html_safe
			%th= t('parameter.value').html_safe
			%th

		%tbody
			- parameters.each do |param|
				%tr
					%td= link_to param.name, admin_parameter_path(param)
					%td= param.description.truncate(55, :omission => '...') if param.description
					%td= param.value
					%td
						= link_to edit_admin_parameter_path(param), :class => 'btn btn-small', :title => t('parameter.edit').html_safe do
							%i.icon-edit

	= paginate parameters

app/views/admin/parameters/edit.html.haml
%legend
	%h2= [t('titles.edit'), @parameter.name].join(" ").html_safe

= render :partial => 'form'

app/views/admin/parameters/index.html.haml
.bartitle
	%h2.pull-left= t('model.parameter').html_safe
	.btn-toolbar.text-right
		.btn-group
			= link_to new_admin_parameter_path, :class => 'btn', :title => t('parameter.new').html_safe do
				%i.icon-plus
					
	.well.form-actions
		%form.form-search
			= text_field_tag :q, nil, :placeholder => t('parameter.search').html_safe, :class => 'searchbar pull-left', 'data-provide' => 'typeahead', :klass => "parameters"
			= link_to admin_reset_path('parameters'), :remote => true, :class => 'btn reset', :title => t('titles.reset').html_safe do
				%i.icon-retweet

	#parameters.partial
		= render :partial => 'listing', :locals => {:parameters => @objects}

app/views/admin/parameters/new.html.haml
%legend
	%h2= t('collection.new').html_safe

= render :partial => 'form'

app/views/admin/parameters/show.html.haml
%legend.bartitle
	%h2.pull-left= @parameter.name.html_safe if @parameter.name
	.btn-toolbar.text-right 
		.btn-group
			= link_to edit_admin_parameter_path(@parameter), :class => 'btn', :title => t('parameter.edit').html_safe do
				%i.icon-edit

%dl.dl-horizontal
	%dt= t('parameter.name').html_safe
	%dd= @parameter.name.html_safe 
	%dt= t('parameter.description').html_safe
	%dd= @parameter.description.html_safe if @parameter.description
	%dt= t('parameter.value').html_safe
	%dd= @parameter.value.html_safe 

= link_to t('helpers.submit.back').html_safe, :back, :class => 'btn'