config/routes.rb
Bpifind::Application.routes.draw do

  root :to => 'home#index'
  devise_for :users

  namespace :admin do
		match '/' => 'dashboard#index'	
		get 'search'
		get 'filter'
		get 'reset'
		resources :collections do
			resources :harvest_logs do
				collection do
					get 'destroy_all'
				end
			end
		end
  	resources :collections_groups 
  	resources :collection_types
		resources :harvest_schedules 
		resources :harvest_logs 
		resources :parameters 
  	resources :users 
  end
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/collection.rb
class Collection < ActiveRecord::Base
	attr_accessible :name, :full_name, :host, :user, :password, :connection_type, :record_schema, :definition, :word, :url
	validates_presence_of :name, :full_name, :host, :user, :password

	has_many :harvest_logs
	has_and_belongs_to_many :collections_groups
	has_and_belongs_to_many :harvest_schedules

	def last_harvest
		harvest_logs.order('start desc').first
	end

	class << self
		def by_harvest_status(status)
			return case status
				when '0' then all
				when '4' then all.select {|c| c.harvest_logs.empty?}
				else all.select {|c| c.last_harvest.status.to_s == status.to_s if c.last_harvest}
			end
		end

		def multiselect_format
			all.collect {|c| [c.full_name, c.id]}
		end
	end
end

app/models/collection_type.rb
class CollectionType < ActiveRecord::Base
  attr_accessible :name, :full_name, :description
	validates_presence_of :name, :full_name

	has_many :collections_groups
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < AdminController

	before_filter :find_collection, :only => [:show, :edit, :update, :destroy]

	def find_collection
		@collection = Collection.find(params[:id])
	end

  def index
    @objects = Collection.order(Collection.sort_column).page(params[:page])
  end

	def show
		@collections_groups = @collection.collections_groups
	end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(params[:collection])
		if @collection.save
			redirect_to admin_collection_path(@collection), notice: t('collection.created', :name => @collection.full_name) 
		else
			render action: "new" 
		end
  end

  def update
		if @collection.update_attributes(params[:collection])
			redirect_to admin_collection_path(@collection), notice: t('collection.updated', :name => @collection.name) 
		else
			render action: "edit" 
		end
  end

  def destroy
		name = @collection.full_name
    @collection.destroy
    redirect_to admin_collections_path, notice: t('collection.destroyed', :name => name ) 
  end

end

app/helpers/collections_helper.rb
module CollectionsHelper

	def last_harvest(collection)
		harvest = collection.last_harvest
		if harvest
			if harvest.success
				display = time_ago_in_words(harvest.start) 
				display += harvest.too_old? ? harvest_duration(harvest) : ''
			else
				display = t('collection.failed')
			end
		else
			display = t('collection.none')
		end
		return display
	end

end

app/views/admin/collections/_form.html.haml
= simple_form_for [:admin, @collection], :html => {:class => 'form-horizontal well'} do |f|
	= f.input :name
	= f.input :full_name
	= f.input :host
	= f.input :user, input_html: { :autocomplete => :off }
	= f.input :password, input_html: { :autocomplete => :off }
	= f.button :submit
	= link_to t('helpers.submit.cancel').html_safe, admin_collections_path, :class => 'btn'

app/views/admin/collections/_listing.html.haml
- unless collections.empty?

	.pull-left{:style => 'margin-top: 10px'}
		= [collections.total_count.to_s, t('model.collection').downcase].join(" ")
	= paginate collections
	%table.table
		%tr
			%th= t('collection.id').html_safe
			%th= t('collection.name').html_safe
			%th= t('collection.host').html_safe
			%th= t('collection.last_harvest').html_safe
			%th
		%tbody
			- collections.each do |collection|
				%tr{:class => harvest_success(collection.last_harvest)}
					%td= collection.id
					%td= link_to collection.full_name.html_safe, admin_collection_path(collection)
					%td= collection.host.truncate(30, :omission => '...').html_safe
					- if collection.harvest_logs.empty?
						%td= last_harvest(collection).html_safe
					- else
						%td= link_to last_harvest(collection).html_safe, admin_collection_harvest_logs_path(collection)
					%td
						= link_to edit_admin_collection_path(collection), :class => 'btn btn-small', :title => t('collection.edit').html_safe do
							%i.icon-edit
						= link_to admin_collection_path(collection), :class => 'btn btn-small', :title => t('collection.destroy').html_safe, method: :delete, data: { confirm: t('collection.confirm_destroy').html_safe } do
							%i.icon-remove
						= link_to edit_admin_collection_path(collection), :class => 'btn btn-small', :title => t('collection.new_harvest').html_safe do
							%i.icon-time

= paginate collections

app/views/admin/collections/edit.html.haml
%legend
	%h2= @collection.full_name.html_safe if @collection.full_name

= render :partial => 'form'

app/views/admin/collections/index.html.haml
.bartitle
	%h2.pull-left= t('model.collection').html_safe
	.btn-toolbar.text-right
		.btn-group
			= link_to new_admin_collection_path, :class => 'btn', :title => t('collection.new').html_safe do
				%i.icon-plus

	.well.form-actions
		%form.form-search
			= text_field_tag :q, nil, :placeholder => t('collection.search').html_safe, :class => 'searchbar pull-left', 'data-provide' => 'typeahead', :klass => "collections"
			%label{:for => 'status'} 
				= t('collection.status').html_safe
			= select_tag :harvest_status, options_for_select(statuses), :class => 'large filter', :klass => "collections"
			= link_to admin_reset_path('collections'), :remote => true, :class => 'btn reset', :title => t('titles.reset').html_safe do
				%i.icon-retweet

	#collections.partial
		= render :partial => 'listing', :locals => {:collections => @objects}

app/views/admin/collections/new.html.haml
%legend
	%h2= t('collection.new').html_safe

= render :partial => 'form'

app/views/admin/collections/show.html.haml
%legend.bartitle
	%h2.pull-left= @collection.full_name.html_safe if @collection.full_name
	.btn-toolbar.text-right 
		.btn-group
			= link_to edit_admin_collection_path(@collection), :class => 'btn', :title => t('collection.edit').html_safe do
				%i.icon-edit
			= link_to admin_collection_path(@collection), :class => 'btn', :title => t('collection.destroy').html_safe, method: :delete, data: { confirm: t('collection.confirm_destroy').html_safe } do
				%i.icon-remove

%dl.dl-horizontal
	%dt= t('collection.name').html_safe
	%dd= @collection.name.html_safe 
	%dt= t('collection.host').html_safe
	%dd= @collection.host.html_safe 
	%dt= t('collection.user').html_safe
	%dd= @collection.user.html_safe 
	%dt= t('collection.password').html_safe
	%dd= @collection.password.html_safe 
	%dt= t('collection.last_harvest').html_safe
	- if @collection.harvest_logs.empty?
		%dd= last_harvest(@collection).html_safe 
	- else
		%dd= link_to last_harvest(@collection).html_safe, admin_collection_harvest_logs_path(@collection)
	%dt= t('model.collections_group').html_safe
	- if @collections_groups.empty?
		%dd= t('helpers.words.none')
	- else 
		- @collections_groups.each do |cg|
			%dd= link_to cg.full_name, admin_collections_group_path(cg)

= link_to t('helpers.submit.back').html_safe, :back, :class => 'btn'