config/routes.rb
Bpifind::Application.routes.draw do

  root :to => 'home#index'
  devise_for :users

  namespace :admin do
		match '/' => 'dashboard#index'	
		get 'search'
		get 'filter'
		get 'reset'
		resources :collections do
			resources :harvest_logs do
				collection do
					get 'destroy_all'
				end
			end
		end
  	resources :collections_groups 
  	resources :collection_types
		resources :harvest_schedules 
		resources :harvest_logs 
		resources :parameters 
  	resources :users 
  end
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/collections_group.rb
class CollectionsGroup < ActiveRecord::Base
  attr_accessible :name, :full_name, :description, :enabled, :collection_type_id
	validates_presence_of :name, :full_name, :collection_type_id

	belongs_to :collection_type
	has_and_belongs_to_many :collections

	class << self

		def by_collection_type(type)
			type == '0' ? all : joins(:collection_type).where('collection_type_id' => type)
		end

		def by_activation(id)
			id = [0, 1] unless id != 'all'
			where('enabled in (?)', id)
		end
	end
end

app/controllers/admin/collections_groups_controller.rb
class Admin::CollectionsGroupsController < AdminController

	before_filter :find_collections_group, :only => [:show, :edit, :update, :destroy]

	def find_collections_group
		@collections_group = CollectionsGroup.find(params[:id])
	end
	
  def index
    @objects = CollectionsGroup.order(CollectionsGroup.sort_column).page(params[:page])
  end

	def show
		@collection_type = @collections_group.collection_type
		@collections = @collections_group.collections
	end

  def new
    @collections_group = CollectionsGroup.new
  end

  def create
    @collections_group = CollectionsGroup.new(params[:collections_group])
		if @collections_group.save
			redirect_to admin_collections_group_path(@collections_group), notice: t('collections_group.created', :name => @collections_group.full_name) 
		else
			render action: "new" 
		end
  end

  def update
		if @collections_group.update_attributes(params[:collections_group])
			redirect_to admin_collections_group_path(@collections_group), notice: t('collections_group.updated', :name => @collections_group.name) 
		else
			render action: "edit" 
		end
  end

  def destroy
		name = @collections_group.full_name
    @collections_group.destroy
    redirect_to admin_collections_groups_path, notice: t('collections_group.destroyed', :name => name ) 
  end

end

app/views/admin/collections_groups/_form.html.haml
= simple_form_for [:admin, @collections_group], :html => {:class => 'form-horizontal well'} do |f|
	= f.input :name
	= f.input :full_name
	= f.input :description
	= f.association :collection_type, :prompt => t('collection_type.choose').html_safe
	= f.input :enabled, :as => :boolean
	= f.button :submit
	= link_to t('helpers.submit.cancel').html_safe, admin_collections_groups_path, :class => 'btn'

app/views/admin/collections_groups/_listing.html.haml
- unless collections_groups.empty?

	.pull-left{:style => 'margin-top: 10px'}
		= [collections_groups.total_count.to_s, t('helpers.words.results')].join(" ").html_safe
	= paginate collections_groups
	%table.table
		%tr
			%th= t('collections_group.full_name').html_safe
			%th= t('collections_group.name').html_safe
			%th= t('collections_group.description').html_safe
			%th= t('collections_group.collection_type').html_safe
			%th= t('collections_group.enabled').html_safe
			%th
		%tbody
			- collections_groups.each do |collections_group|
				%tr{:class => collections_group.enabled ? 'success' : 'error'}
					%td= link_to collections_group.full_name.html_safe, admin_collections_group_path(collections_group)
					%td= collections_group.name
					%td= collections_group.description.truncate(30, :omission => '...').html_safe
					%td= link_to collections_group.collection_type.full_name.html_safe, admin_collection_type_path(collections_group.collection_type) if collections_group.collection_type
					%td= collections_group.enabled ? t('helpers.words.yeslabel') : t('helpers.words.nolabel')
					%td
						= link_to edit_admin_collections_group_path(collections_group), :class => 'btn btn-small', :title => t('collections_group.edit').html_safe do
							%i.icon-edit
						= link_to admin_collections_group_path(collections_group), :class => 'btn btn-small', :title => t('collections_group.destroy').html_safe, method: :delete, data: { confirm: t('collections_group.confirm_destroy').html_safe } do
							%i.icon-remove

	= paginate collections_groups

app/views/admin/collections_groups/edit.html.haml
%legend
	%h2= @collections_group.full_name.html_safe if @collections_group.full_name

= render :partial => 'form'

app/views/admin/collections_groups/index.html.haml
.bartitle
	%h2.pull-left= t('model.collections_group').html_safe
	.btn-toolbar.text-right
		.btn-group
			= link_to new_admin_collections_group_path, :class => 'btn', :title => t('collections_group.new').html_safe do
				%i.icon-plus

	.well.form-actions
		%form.form-search
			= text_field_tag :q, nil, :placeholder => t('collections_group.search').html_safe, :class => 'searchbar pull-left', 'data-provide' => 'typeahead', :klass => "collections_groups"
			%label{:for => 'collection_type'} 
				= t('model.collection_type').html_safe
			= select_tag :collection_type, options_for_select(types), :class => 'large filter', :klass => 'collections_groups'
			%label{:for => 'enabled'} 
				= t('collections_group.enabled').html_safe
			= select_tag :activation, options_for_select(booleans), :class => 'small filter', :klass => 'collections_groups'
			= link_to admin_reset_path('collections_groups'), :remote => true, :class => 'btn reset', :title => t('titles.reset').html_safe do
				%i.icon-retweet

	#collections_groups.partial
		= render :partial => 'listing', :locals => {:collections_groups => @objects}

app/views/admin/collections_groups/new.html.haml
%legend
	%h2= t('collections_group.new').html_safe

= render :partial => 'form'

app/views/admin/collections_groups/show.html.haml
%legend.bartitle
	%h2.pull-left= @collections_group.full_name.html_safe if @collections_group.full_name
	.btn-toolbar.text-right 
		.btn-group
			= link_to edit_admin_collections_group_path(@collections_group), :class => 'btn', :title => t('collections_group.edit').html_safe do
				%i.icon-edit
			= link_to admin_collections_group_path(@collections_group), :class => 'btn', :title => t('collections_group.destroy').html_safe, method: :delete, data: { confirm: t('collections_group.confirm_destroy').html_safe } do
				%i.icon-remove

%dl.dl-horizontal
	%dt= t('collections_group.name').html_safe
	%dd= @collections_group.name.html_safe 
	%dt= t('collections_group.description').html_safe
	%dd= @collections_group.description.html_safe 
	%dt= t('collections_group.collection_type').html_safe
	%dd= link_to @collection_type.full_name, admin_collection_type_path(@collection_type)
	%dt= t('collections_group.enabled').html_safe
	%dd= @collections_group.enabled ? t('helpers.words.yeslabel') : t('helpers.words.nolabel') 
	%dt= t('model.collection').html_safe
	- if @collections.empty?
		%dd= t('helpers.words.none')
	- else
		- @collections.each do |c|
			%dd= link_to c.full_name, admin_collection_path(c)


= link_to t('helpers.submit.back').html_safe, :back, :class => 'btn'