config/routes.rb
Bpifind::Application.routes.draw do

  root :to => 'home#index'
  devise_for :users

  namespace :admin do
		match '/' => 'dashboard#index'	
		get 'search'
		get 'filter'
		get 'reset'
		resources :collections do
			resources :harvest_logs do
				collection do
					get 'destroy_all'
				end
			end
		end
  	resources :collections_groups 
  	resources :collection_types
		resources :harvest_schedules 
		resources :harvest_logs 
		resources :parameters 
  	resources :users 
  end
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/admin/parts/_bar.html.haml
.navbar
	.navbar-inner
		= link_to 'Home', '#', :class => 'brand'
		%ul.nav
			%li= link_to 'test1', admin_collections_path
			%li= link_to 'test2', admin_parameters_path

		%ul.nav.pull-right
			%li.pull-right
				= link_to "#{current_user.name} (#{current_user.email})", edit_admin_user_path(current_user)
			%li.pull-right
				= link_to destroy_user_session_path, :method => 'delete', :style => "padding: 12px 0 11px;", :alt => t('devise.logout').html_safe do
					= image_tag "exclamation.png", :style => "width: 15px;", :alt => t('devise.logout').html_safe, :title => t('devise.logout').html_safe

app/views/admin/parts/_menu.html.haml
.menu.well
	%ul.nav.nav-list
		%li.nav-header
			Collections
		%li
			= link_to t('model.collection').html_safe, admin_collections_path
		%li
			= link_to t('model.collection_type').html_safe, admin_collection_types_path
		%li
			= link_to t('model.collections_group').html_safe, admin_collections_groups_path
		%li.nav-header
			Moissons
		%li
			= link_to t('model.harvest_schedules').html_safe, admin_harvest_schedules_path
		%li.nav-header
			Application
		%li
			= link_to t('model.user').html_safe, admin_users_path
		%li
			= link_to t('model.parameter').html_safe, admin_parameters_path